name: "CI/CD"

on: [push]

jobs:
  build:
    name: "Compile"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - run: yarn install --froze-lockfile --prefer-offline

      - run: NODE_ENV=production yarn compile
